FROM ubuntu:latest

RUN apt update 

RUN apt upgrade -y

RUN apt install git -y

# COPY ./ /workspace

# RUN adduser developer

# RUN chown -R developer:developer /workspace

# USER developer

# WORKDIR /workspace
